---
- name: Deploy Coolstore Microservices Demo
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
    - demo_vars/msa/all

  tasks:
    - include_role:
        name: "{{ ANSIBLE_REPO_PATH }}/roles/{{ env_type }}-common"

    - import_role:
        name: "{{ ANSIBLE_REPO_PATH }}/roles/{{ env_type }}-openshift_coolstore"
      vars:
        project_annotations: "demo=demo-msa-{{ project_suffix }}"
        hostname_suffix: "{{ apps_hostname_suffix }}"
        enable_cicd: false
        prune_builds_selector: "comp-required!=true"
        prune_deployments_selector: "comp-required!=true"
