---
- hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
    - "env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
  vars:
    repo: https://github.com/siamaksade/openshift-demos-ansible.git

  tasks:
    - name: Create temporary directory
      tempfile:
        state: directory
      register: tempdir

    - name: "Clone {{repo}}"
      git:
        repo: "{{repo}}"
        depth: 1
        dest: "{{tempdir.path}}/"

    - find:
        file_type: directory
        paths: "{{tempdir.path}}/roles/"
      register: roles

    - name: Copy roles from repository to ansible/roles
      copy:
        src: "{{item}}/"
        dest: "{{ ANSIBLE_REPO_PATH }}/roles/{{ env_type }}-{{item|basename}}"
        force: no
      with_items: "{{roles|json_query('files[].path')}}"

    - name: Remove temporary directory
      file:
        path: "{{tempdir.path}}"
        state: absent
